"""
Database Module

Handles all database operations using SQLAlchemy.

Tables:
    - teams: Stores team info (name, API ID, competition)
    - matches: Stores match results (scores, winner, date)
    - match_features: Stores computed ML features per match (form, goals avg, h2h)
    - predictions: Stores model predictions and evaluation results
"""

from sqlalchemy import create_engine, Column, Integer, String, Float, DateTime, ForeignKey, Boolean
from sqlalchemy.orm import sessionmaker, relationship, declarative_base
from datetime import datetime
from dotenv import load_dotenv
import os

load_dotenv()

# Database connection setup — reads DATABASE_URL from .env file
# Falls back to local PostgreSQL if not set
DATABASE_URL = os.getenv('DATABASE_URL', 'postgresql://postgres:password@localhost/football_predictor')
engine = create_engine(DATABASE_URL)
SessionLocal = sessionmaker(bind=engine)  # Factory for creating database sessions
Base = declarative_base()  # Base class for all ORM models

# ============================================================
# ORM Models — define the database table structure
# ============================================================

class Team(Base):
    """Stores football team information. Linked to matches via foreign keys."""
    __tablename__ = 'teams'

    id = Column(Integer, primary_key=True, index=True)
    api_id = Column(Integer, unique=True, nullable=False) # ID from API
    name = Column(String(100), nullable=False)
    short_name = Column(String(50))
    competition = Column(String(100))

    # Relationships — a team can be home or away in many matches
    home_matches = relationship("Match", foreign_keys="Match.home_team_id", back_populates="home_team")
    away_matches = relationship("Match", foreign_keys="Match.away_team_id", back_populates="away_team")

    created_at = Column(DateTime, default=datetime.utcnow)

class Match(Base):
    """Stores individual match results. Each match links to two teams (home/away)."""
    __tablename__ = 'matches'

    id = Column(Integer, primary_key=True, index=True)
    api_id = Column(Integer, unique=True, nullable=False)

    # Teams
    home_team_id = Column(Integer, ForeignKey('teams.id'), nullable=False)
    away_team_id = Column(Integer, ForeignKey('teams.id'), nullable=False)

    # Match details
    season = Column(Integer, nullable=False)
    matchday = Column(Integer)
    competition = Column(String(100), nullable=False)
    date = Column(DateTime, nullable=False)
    status = Column(String(20), nullable=False)

    # Scores 
    home_score = Column(Integer)
    away_score = Column(Integer)
    winner = Column(String(20)) # HOME_TEAM, AWAY_TEAM, DRAW

    # Relationships — link back to teams and forward to features/predictions
    # uselist=False means one-to-one (each match has one feature set and one prediction)
    home_team = relationship("Team", foreign_keys=[home_team_id], back_populates="home_matches")
    away_team = relationship("Team", foreign_keys=[away_team_id], back_populates="away_matches")
    features = relationship("MatchFeatures", back_populates="match", uselist=False)
    prediction = relationship("Prediction", back_populates="match", uselist=False)

    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

class MatchFeatures(Base):
    """Computed ML features for each match. Generated by feature_engineering.py."""
    __tablename__ = 'match_features'

    id = Column(Integer, primary_key=True, index=True)
    match_id = Column(Integer, ForeignKey('matches.id'), unique=True, nullable=False)

    # Form features — average points per game over last 5 matches
    home_form_5 = Column(Float)
    away_form_5 = Column(Float)

    # Goal averages — rolling mean of goals scored/conceded over recent matches
    home_goals_scored_avg = Column(Float)
    home_goals_conceded_avg = Column(Float)
    away_goals_scored_avg = Column(Float)
    away_goals_conceded_avg = Column(Float)

    # Head-to-head record — results from last 5 meetings between these two teams
    h2h_home_wins = Column(Integer)
    h2h_draws = Column(Integer)
    h2h_away_wins = Column(Integer)

    # Strength indicators — overall win rate and rest days
    home_win_rate = Column(Float)  # Cumulative home win percentage
    away_win_rate = Column(Float)  # Cumulative away win percentage
    days_since_home_last_match = Column(Integer)  # Rest days for home team
    days_since_away_last_match = Column(Integer)  # Rest days for away team

    # Relationship
    match = relationship("Match", back_populates="features")

    created_at = Column(DateTime, default=datetime.utcnow)

class Prediction(Base):
    """Stores ML model predictions. Evaluated after match is played (correct column)."""
    __tablename__ = 'predictions'

    id = Column(Integer, primary_key=True, index=True)
    match_id = Column(Integer, ForeignKey('matches.id'), unique=True, nullable=False)

    # Prediction
    predicted_winner = Column(String(20)) # HOME_TEAM, AWAY_TEAM, DRAW
    home_win_prob = Column(Float)
    draw_prob = Column(Float)
    away_win_prob = Column(Float)
    confidence = Column(Float) # Max probability

    # Model info
    model_version = Column(String(50))
    model_type = Column(String(50)) # 'xgboost', 'random_forest', etc.

    # Evaluation (filled after match is played)
    actual_winner = Column(String(50))
    correct = Column(Boolean)

    # Relationship
    match = relationship("Match", back_populates="prediction")

    created_at = Column(DateTime, default=datetime.utcnow)

# ============================================================
# Database utility functions
# ============================================================

def init_db():
    """Create all tables in the database based on the ORM models above."""
    Base.metadata.create_all(bind=engine)
    print("Database tables created successfully!")

def get_db():
    """Yield a database session, ensuring it's closed after use."""
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()

# ============================================================
# DatabaseManager — high-level CRUD operations
# ============================================================

class DatabaseManager:
    """Provides methods to add/query teams and matches. Handles upsert logic."""

    def __init__(self):
        self.session = SessionLocal()

    def close(self):
        """Close database session"""
        self.session.close()

    def add_team(self, api_id, name, short_name, competition):
        """Add a new team or update existing one (matched by api_id)."""
        team = self.session.query(Team).filter_by(api_id=api_id).first()

        if team:
            # Update existing
            team.name = name
            team.short_name = short_name
            team.competition = competition
        else:
            # Create new
            team = Team(
                api_id=api_id,
                name=name,
                short_name=short_name,
                competition = competition
            )
            self.session.add(team)

        self.session.commit()
        return team
    
    def add_match(self, match_data):
        """Add a new match or update scores/status if it already exists."""
        match = self.session.query(Match).filter_by(api_id=match_data['api_id']).first()

        # Get or create teams
        home_team = self.session.query(Team).filter_by(api_id=match_data['home_team_api_id']).first()
        away_team = self.session.query(Team).filter_by(api_id=match_data['away_team_api_id']).first()

        if match:
            # Update existing
            match.home_score = match_data.get('home_score')
            match.away_score = match_data.get('away_score')
            match.winner = match_data.get('winner')
            match.status = match_data.get('status')
        else:
            # Create new
            match = Match(
                api_id=match_data['api_id'],
                home_team_id=home_team.id,
                away_team_id=away_team.id,
                season=match_data['season'],
                matchday=match_data.get('matchday'),
                competition=match_data['competition'],
                date=match_data['date'],
                status=match_data['status'],
                home_score=match_data.get('home_score'),
                away_score=match_data.get('away_score'),
                winner=match_data.get('winner')
            )
            self.session.add(match)

        self.session.commit()
        return match

    def get_team_matches(self, team_id, limit=None):
        """Get all matches where team played (home or away), ordered by date descending."""
        query = self.session.query(Match).filter(
            (Match.home_team_id == team_id) | (Match.away_team_id == team_id)
        ).order_by(Match.date.desc())

        if limit:
            query = query.limit(limit)
        
        return query.all()
    
    def get_all_matches(self):
        """Get all matches"""
        return self.session.query(Match).order_by(Match.date.desc()).all()
    
# Main execution
if __name__ == "__main__":
    print("Initializing database...")
    init_db()
    print("Database ready!")

